name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Remove PS3 and Wii files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Move songs_xbox folder to _ark
        run: |
          mv _songs/songs_xbox _ark/songs
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5 -s 4073741823
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRBUL-Xbox
          path: _build/xbox

  build_ps3_usa:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove Xbox and Wii files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Move songs_ps3 folder to _ark
        run: |
          move _songs\songs_ps3 _ark\songs
      - name: Build ARK
        run: |
          dependencies/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      - name: Build PKG
        run: |
          move "dependencies\ta_pkg_repacker_tools\usa\PARAM.SFO" "_build\ps3"
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLUS30382_00-LRBULTIMA"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/usa/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRBUL-PS3-USA
          path: '*.pkg'

  build_ps3_eur:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove Xbox and Wii files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Move songs_ps3 folder to _ark
        run: |
          move _songs\songs_ps3 _ark\songs
      - name: Build ARK
        run: |
          dependencies/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      - name: Build PKG
        run: |
          Remove-Item "_build\ps3\USRDIR\EBOOT.BIN" -Force
          move "dependencies\eu_eboot\EBOOT.BIN" "_build\ps3\USRDIR"
          move "dependencies\ta_pkg_repacker_tools\eur\PARAM.SFO" "_build\ps3"
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLES00636_00-LRBULTIMA"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/eur/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRBUL-PS3-EUR
          path: '*.pkg'

  build_wii_riivolution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          mkdir -p ./dependencies/riivolution-patch/lrbul/
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          mkdir -p _build/wii_riivolution/lrbul
          cp dependencies/wii_rebuild_file/main_wii.hdr dependencies/riivolution-patch/lrbul/main_wii.hdr
          truncate -s 1994575183 dependencies/riivolution-patch/lrbul/main_wii_0.ark
          truncate -s 1595018582 dependencies/riivolution-patch/lrbul/main_wii_1.ark
      - name: Remove Xbox and PS3 files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_ps3" -type f -delete
      - name: Move songs_wii folder to _ark
        run: |
          mv _songs/songs_wii _ark/songs

      - name: Build ARK
        run: |
          dependencies/linux/arkhelper patchcreator -a ./_ark -o ./dependencies/riivolution-patch/lrbul dependencies/riivolution-patch/lrbul/main_wii.hdr dependencies/patch/main.dol
      - name: Move generated Wii files to proper folder
        run: |
          mv -f dependencies/riivolution-patch/lrbul/gen/main_wii.hdr dependencies/riivolution-patch/lrbul/main_wii.hdr
          mv -f dependencies/riivolution-patch/lrbul/gen/main_wii_2.ark dependencies/riivolution-patch/lrbul/main_wii_2.ark
          rmdir dependencies/riivolution-patch/lrbul/gen
          rm dependencies/riivolution-patch/lrbul/main.dol
          rm dependencies/riivolution-patch/lrbul/main_wii_0.ark
          rm dependencies/riivolution-patch/lrbul/main_wii_1.ark
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRBUL-Wii-Riivolution
          path: dependencies/riivolution-patch

  build_wii_patcher_usa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Remove Xbox and PS3 files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_ps3" -type f -delete
      - name: Move songs_wii folder to _ark
        run: |
          mv _songs/songs_wii _ark/songs
      - name: Create necessary directories and copy files for patcher
        run: |
          mkdir -p ./_build/wii/ultimate_files/sys/
          mkdir -p ./_build/wii/ultimate_files/files/gen/
          mkdir -p ./_build/wii/iso
          mkdir -p ./_build/wii/wit
          cp dependencies/patch/main.dol ./_build/wii/ultimate_files/sys/main.dol
          cp dependencies/patch/setup.txt ./_build/wii/ultimate_files/setup.txt
          cp dependencies/wii_rebuild_file/main_wii.hdr ./_build/wii/ultimate_files/files/gen/main_wii.hdr
          truncate -s 1994575183 ./_build/wii/ultimate_files/files/gen/main_wii_0.ark
          truncate -s 1595018582 ./_build/wii/ultimate_files/files/gen/main_wii_1.ark
          cp -r dependencies/wii-patcher/* ./_build/wii
          cp -r dependencies/wit/* ./_build/wii/wit
          cp -r iso/* ./_build/wii/iso

      - name: Build ARK
        run: |
          dependencies/linux/arkhelper patchcreator -a ./_ark -o ./_build/wii/ultimate_files/files/gen ./_build/wii/ultimate_files/files/gen/main_wii.hdr dependencies/patch/main.dol
      - name: Move generated Wii files to proper folder
        run: |
          mv -f ./_build/wii/ultimate_files/files/gen/gen/main_wii.hdr ./_build/wii/ultimate_files/files/gen/main_wii.hdr
          mv -f ./_build/wii/ultimate_files/files/gen/gen/main_wii_2.ark ./_build/wii/ultimate_files/files/gen/main_wii_2.ark
          rmdir ./_build/wii/ultimate_files/files/gen/gen
          rm ./_build/wii/ultimate_files/files/gen/main.dol
          rm ./_build/wii/ultimate_files/files/gen/main_wii_0.ark
          rm ./_build/wii/ultimate_files/files/gen/main_wii_1.ark
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: LRBUL-Wii-Patcher-USA
          path: _build/wii
